sudo: false
language: node_js
node_js:
  - 'node'
  - '6'
  - '5'
  - '4'
before_script:
  - npm install -g bower
  - bower install -f
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
